### ISSUE TITLE
Implement Identity Management with Single Sign-On

### ISSUE THREAD

**Issue by AKissMail** [AKissMail/MIRAGEXR_AI_service-backend#72]
Implement identity management using Single Sign-On (SSO) via Keycloak. Ensure that users can authenticate once and gain access to multiple services.

- Integrate the existing Keycloak instances with the API Gateway for user authentication.
- Test and create a unit test for the SSO functionality with multiple services.
- Document the SSO setup and usage guidelines.

**Comment by AKissmehl** [comment]
see #69
